### ISSUE TITLE
Questions about experiment results

### ISSUE THREAD

**Issue by pascal1129** [hzhupku/SemiSeg-AEL#1]
Hi, I find [CPS](https://openaccess.thecvf.com/content/CVPR2021/papers/Chen_Semi-Supervised_Semantic_Segmentation_With_Cross_Pseudo_Supervision_CVPR_2021_paper.pdf) was cited in your paper, but you didn't compare your method with it, which made me quite confused.

**Comment by hzhupku** [comment]
CPS was not publicly available during neurips 2021 submission.
