### ISSUE TITLE
Multi-scale evaluation?

### ISSUE THREAD

**Issue by Haochen-Wang409** [hzhupku/SemiSeg-AEL#11]
Hi, it seems that you use multi-scale evaluation: https://github.com/hzhupku/SemiSeg-AEL/blob/main/eval.py#L37
Are the results in your papers under this setting? How about previous SOTA methods?

**Comment by Haochen-Wang409** [comment]
Besides, in your paper section 4.1, your method was evaluated under single scale.

**Comment by hzhupku** [comment]
Check out the evaluation command in train.sh. We use single scale evaluation.
