### ISSUE TITLE
Question for your few supervision splits in VOC?

### ISSUE THREAD

**Issue by ghost** [hzhupku/SemiSeg-AEL#13]
I can't reproduce your results based on the aug set of the ratio of 1/32 and 1/16.

In 1/16(662), with the partitioning protocol of the CPS, I only have **75.64** with 4*v100 GPUs, where every single GPU with batch size = 16, and 513x513 as input resolution. It is far lower than your reported results in your paper.

**For these two ratios, do you split your data based on the entire aug dataset, or the high-quality set**

Can you provide your splits?

Cheers

**Comment by LiheYoung** [comment]
Hi @Sun-Rider,

Have you reproduced the results as the paper?
