### ISSUE TITLE
Could you provide the splits?

### ISSUE THREAD

**Issue by Haochen-Wang409** [hzhupku/SemiSeg-AEL#2]
Hi, thanks for your great work. I wonder if you could provide splits (which images are considered as labeled data) for both PASCAL VOC and Cityscapes? Because even if the random seed is set, there may be a certain uncertainty when sampling.

**Comment by hzhupku** [comment]
For semi-supervised setting, there is no need to perform experiments on the exact same splits. Running multiple times with different seeds is preferable.

**Comment by ghost** [comment]
> For semi-supervised setting, there is no need to perform experiments on the exact same splits. Running multiple times with different seeds is preferable.

It is not true. In pascal voc12, there are both two kinds of high-quality and low-level aug pixel-wise labels. In case you put more high-quality labels in the labelled set, your results will be significantly boosted, especially under the 5291 (1/2 partition protocol).  Could you please share you splits. Thanks.
