### ISSUE TITLE
Question about ignore_cat 

### ISSUE THREAD

**Issue by lliuz** [hzhupku/SemiSeg-AEL#4]
Hi @hzhupku, thanks for sharing. I have a question when I read your code:
https://github.com/hzhupku/SemiSeg-AEL/blob/747c7972a1aed589a8a62cdd98c3d1836c609735/train.py#L193
Can you explain why you set `ignore_cat`  to `[0, 1, 2, 8, 10]`, and it seems like be same for pascal voc and cityscapes?

**Comment by lliuz** [comment]
Besides, I don't see the need for `class_criterion` to be shape of `3xC`.
https://github.com/hzhupku/SemiSeg-AEL/blob/747c7972a1aed589a8a62cdd98c3d1836c609735/train.py#L126
It seems that only the first row is used in the code.

**Comment by hzhupku** [comment]
(1) ignore_cat is only used for Cityscapes;
(2) yes, we experiment with three criterions, but only use the first one.
