### ISSUE TITLE
Data / Resnet

### ISSUE THREAD

**Issue by dd1github** [hzhupku/SemiSeg-AEL#5]
Hi,

Is there a link to the data?  I registered and downloaded the gtfine dataset from the Cityscapes website.  Is that the right one -it provides a bunch of subfolders for cities?  The download did not contain a datalist - fine_train.txt and fine_test.txt.  How do we obtain those?  Also, is there a link to the resnet model?

**Comment by hzhupku** [comment]
You have to generate the data list yourself. We only use finely annotated data. ResNet pretrain model can be found by searching the file name.
