### ISSUE TITLE
Ohem and Aux_loss for pascal voc? 

### ISSUE THREAD

**Issue by Haochen-Wang409** [hzhupku/SemiSeg-AEL#6]
Hi, sorry to bother you. I found ```ohem``` and ```aux_loss``` are in the config for pascal voc:
https://github.com/hzhupku/SemiSeg-AEL/blob/main/experiments/pascal_4/config.yaml#L61
https://github.com/hzhupku/SemiSeg-AEL/blob/main/experiments/pascal_4/config.yaml#L70

However, these two tricks are not mentioned in your paper.

**Comment by hzhupku** [comment]
We follow the common practice of many state-of-the-art methods.
