### ISSUE TITLE
Typo in paper

### ISSUE THREAD

**Issue by JihwanEom** [hzhupku/SemiSeg-AEL#7]
Hello, thank you for your awesome works!

Typo is on page 9, section 4.7 Qualitative Results second line,

"""
We compare the proposed AEL with ground-truth, **supervsied** baseline and our basic framework described in Section 3.2.
"""

I think supervsied should be supervised :) Ah, I downloaded pdf file on arxiv today.

Thank you.
Jihwan Eom

**Comment by hzhupku** [comment]
Thank you very much for mentioning these. We will correct these in the next version.
